export const PAGES = {
  HOME: '/dashboard',
  GRADES: '/grades',
  ATTENDANCE: '/attendance',
  SCHEDULE: '/schedule',
  DOCUMENTS: '/documents',
  DIARIES: '/diaries',
  GRADING: '/grading',
  STUDENTS_MGMT: '/students-management',
  TEACHERS_MGMT: '/teachers-management',
  REPORTS: '/school-reports',
  TEACHER_ANALYTICS: '/teacher-analytics',
  CLASSES: '/classes',
  SUBJECTS: '/subjects',
  ALLOCATIONS: '/allocations',
  SCHEDULES: '/schedules',
  MATRICULAS: '/matriculas',
};